#!/bin/bash

test_get_commit_pragmas() {
    local msg='Use external action

Run-GHA: true
Skip-PR-comments: true
Test-tag: always_passes,vm

Required-githooks: true

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
'
    assert_equals "$(echo "$msg" | ../get_commit_pragmas)" 'CP_RUN_GHA=true
CP_SKIP_PR_COMMENTS=true
CP_TEST_TAG=always_passes,vm
CP_REQUIRED_GITHOOKS=true
CP_SIGNED_OFF_BY=Brian\ J.\ Murrell\ \<brian.murrell@intel.com\>'

    local msg='Escape spaces also

'"'"'Will-not-be-a-pragma: false'"'"' should not be considered a commit
pragma, but:
Should-not-be-a-pragma: bar will be because it was not quoted.

Skip-func-test-leap15: false
RPM-test-version: 2.5.100-13.10036.g65926e32
Skip-PR-comments: true
Test-tag: always_passes always_fails
EL8-VM9-label: all_vm9
EL9-VM9-label: all_vm9
Leap15-VM9-label: all_vm9
HW-medium-label: new_icx5
HW-large-label: new_icx9

Required-githooks: true

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
'
    assert_equals "$(echo "$msg" | ../get_commit_pragmas)" 'CP_SHOULD_NOT_BE_A_PRAGMA=bar\ will\ be\ because\ it\ was\ not\ quoted.
CP_SKIP_FUNC_TEST_LEAP15=false
CP_RPM_TEST_VERSION=2.5.100-13.10036.g65926e32
CP_SKIP_PR_COMMENTS=true
CP_TEST_TAG=always_passes\ always_fails
CP_EL8_VM9_LABEL=all_vm9
CP_EL9_VM9_LABEL=all_vm9
CP_LEAP15_VM9_LABEL=all_vm9
CP_HW_MEDIUM_LABEL=new_icx5
CP_HW_LARGE_LABEL=new_icx9
CP_REQUIRED_GITHOOKS=true
CP_SIGNED_OFF_BY=Brian\ J.\ Murrell\ \<brian.murrell@intel.com\>'

}
